version: "3.1"

services:
  shibboleth-idp:
    image: shibboleth-idp:9.4.30
    volumes: 
      - ./shibboleth-idp:/opt/shibboleth-idp 
      - ./logs/jetty:/opt/jetty-base/logs 
    ports:
      - 443:443
      - 8443:8443
    depends_on: 
      - rest
    environment: 
      - TZ=Asia/Seoul

  rest:
    image: chrisryu/idp-rest-oracle
    ports:
     - 4000:4000
    env_file: 
     - ./rest-env/db_server_oracle.env
    environment: 
      - TZ=Asia/Seoul

