#!/bin/bash

#
# Run the IdP installer in a container.
#
. VERSIONS

# cp -r ./overlay/shibboleth/edit-webapp/* ./fetched/shibboleth-dist/edit-webapp/

docker run --rm \
    -v `pwd`/shibboleth-idp:/opt/shibboleth-idp \
    -v `pwd`/fetched/shibboleth-dist:/data/shibboleth-dist \
    -v `pwd`/install-idp:/data/install-idp \
    -v `pwd`/overlay/shibboleth:/data/shibboleth-overlay \
    ${JAVA_VERSION} \
    /data/install-idp

cp -r ./overlay/shibboleth/conf/* ./shibboleth-idp/conf/
cp -r ./overlay/shibboleth/metadata/* ./shibboleth-idp/metadata/